"""autogenerated by genpy from mapping/object_detected_info.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class object_detected_info(genpy.Message):
  _md5sum = "0b716302aac05375801fbfea69edc447"
  _type = "mapping/object_detected_info"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint32 objectDetected
uint32 object_x
uint32 object_y
"""
  __slots__ = ['objectDetected','object_x','object_y']
  _slot_types = ['uint32','uint32','uint32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       objectDetected,object_x,object_y

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(object_detected_info, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.objectDetected is None:
        self.objectDetected = 0
      if self.object_x is None:
        self.object_x = 0
      if self.object_y is None:
        self.object_y = 0
    else:
      self.objectDetected = 0
      self.object_x = 0
      self.object_y = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.objectDetected, _x.object_x, _x.object_y))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.objectDetected, _x.object_x, _x.object_y,) = _struct_3I.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.objectDetected, _x.object_x, _x.object_y))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.objectDetected, _x.object_x, _x.object_y,) = _struct_3I.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
