/*
 * Enumerations.h
 *
 *  Created on: 01.12.2013
 *      Author: paul
 */

#ifndef ENUMERATIONS_H_
#define ENUMERATIONS_H_

#include <iostream>
using namespace std;

//TODO: ADD LION TO SURF MODULE TOGETHER WITH ELEPHANT;HIPPO
//1 CHECK LION SEPARATION


enum object{
	TIGER=0,ZEBRA,ELEPHANT,HIPPO,GIRAFFE,LION,				//ANIMALS

	POTATO,TOMATO,ONION,BROCOLI,PAPRIKA,CARROT,CORN,AVOCADO,			//VEGETABLES

	MELON,PEAR,BANANA,ORANGE,LEMON,							//FRUITS

	NUMBER_OF_OBJECTS
};


enum colors{
	BANANA_YELLOW,
	POTATO_BROWN,
	TOMATO_RED,
	ONION_ORANGE,
	BROCOLI_GREEN,
	PAPRIKA_GREEN,
	CARROT_ORANGE,
	CARROT_GREEN,
	CORN_YELLOW,
	LEMON_YELLOW,
	PEAR_GREEN,
	ORANGE_ORANGE,
	MELON_GREEN,
	MELON_RED,
	AVOCADO_GREEN,
	LION_YELLOW,

	NR_OF_COLORS
};





#endif /* ENUMERATIONS_H_ */
